# Generated by Django 4.0.4 on 2022-07-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='description',
            field=models.CharField(default=True, max_length=100000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publication',
            name='title_photo',
            field=models.FileField(upload_to='firstapp/static/img'),
        ),
    ]
