# Generated by Django 4.0.4 on 2022-07-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_publication_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='description',
        ),
        migrations.AddField(
            model_name='publication',
            name='paragraph1',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='publication',
            name='paragraph2',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='publication',
            name='paragraph3',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='publication',
            name='paragraph4',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='publication',
            name='paragraph5',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='publication',
            name='photo1',
            field=models.ImageField(blank=True, upload_to='firstapp/static/img'),
        ),
        migrations.AddField(
            model_name='publication',
            name='photo2',
            field=models.ImageField(blank=True, upload_to='firstapp/static/img'),
        ),
        migrations.AddField(
            model_name='publication',
            name='photo3',
            field=models.ImageField(blank=True, upload_to='firstapp/static/img'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title_photo',
            field=models.ImageField(upload_to='firstapp/static/img'),
        ),
    ]
