# Generated by Django 4.0.4 on 2022-07-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_remove_publication_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='title_photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
