# Generated by Django 4.0.4 on 2022-07-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_alter_publication_title_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='tags',
        ),
        migrations.AddField(
            model_name='publication',
            name='tag1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='publication',
            name='tag2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='publication',
            name='tag3',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='publication',
            name='tag4',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
