# Generated by Django 4.0.4 on 2022-07-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_publication_photo4_publication_photo5_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='paragraph1',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='publication',
            name='paragraph2',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='publication',
            name='paragraph3',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='publication',
            name='paragraph4',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='publication',
            name='paragraph5',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='publication',
            name='section',
            field=models.CharField(choices=[('Политика', 'Политика'), ('Экономика', 'Экономика'), ('Общество', 'Общество'), ('Культура', 'Культура'), ('Спорт', 'Спорт'), ('В мире', 'В мире'), ('Технология', 'Технология')], max_length=100),
        ),
    ]
