# Generated by Django 4.0.4 on 2022-07-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_alter_publication_paragraph1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='preview',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
