# Generated by Django 4.0.4 on 2022-07-23 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_user_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
