# Generated by Django 4.0.4 on 2022-07-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0012_alter_user_profile_pictire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pictire',
            field=models.ImageField(blank=True, default='media/images/profile_picture', upload_to='images/profile_picture'),
        ),
    ]
