# Generated by Django 4.0.4 on 2022-07-24 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0013_alter_user_profile_pictire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcomment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=1000)),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('base_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.user')),
            ],
        ),
    ]
