# Generated by Django 4.0.4 on 2022-07-24 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0014_subcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcomment',
            name='publication',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='firstapp.publication'),
            preserve_default=False,
        ),
    ]
