# Generated by Django 4.0.4 on 2022-07-24 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0015_subcomment_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcomment',
            name='publication',
        ),
    ]
