# Generated by Django 4.0.4 on 2022-07-24 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0016_remove_subcomment_publication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_pictire',
            new_name='profile_picture',
        ),
    ]
