# Generated by Django 4.0.4 on 2022-07-25 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0019_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='profile_picture/default.jpg', upload_to='images/profile_picture'),
        ),
    ]
